import Foundation

enum L10n {
    static func t(_ key: String) -> String {
        let language = Locale.preferredLanguages.first ?? "en"
        let table = language.hasPrefix("zh") ? zh : en
        return table[key] ?? en[key] ?? key
    }

    private static let en: [String: String] = [
        "app_name": "R2Desk",
        "sidebar_title": "Buckets",
        "add_bucket": "Add Bucket",
        "settings": "Settings",
        "refresh": "Refresh",
        "upload": "Upload",
        "open": "Open",
        "delete": "Delete",
        "empty_title": "Select or add a bucket",
        "empty_message": "Your S3 and Cloudflare R2 buckets are stored locally on this Mac.",
        "no_objects": "No objects in this bucket",
        "name": "Name",
        "size": "Size",
        "modified": "Modified",
        "storage_class": "Storage Class",
        "status_ready": "Ready",
        "status_loading": "Loading objects...",
        "status_uploading": "Uploading...",
        "status_opening": "Opening file...",
        "profile_name": "Connection Name",
        "display_name": "Display Name",
        "bucket_name": "Bucket Name",
        "endpoint": "Endpoint URL",
        "region": "Region",
        "access_key": "Access Key ID",
        "secret_key": "Secret Access Key",
        "save": "Save",
        "cancel": "Cancel",
        "new_bucket": "New Bucket",
        "edit_bucket": "Bucket Settings",
        "delete_confirm_title": "Delete object?",
        "delete_confirm_message": "This removes the selected object from the remote bucket.",
        "error_title": "Something went wrong",
        "delete_bucket": "Remove Bucket",
        "delete_bucket_confirm_title": "Remove bucket from R2Desk?",
        "delete_bucket_confirm_message": "This only removes local configuration and Keychain credentials. Remote files are not changed.",
        "local_only": "Local config + Keychain"
        ,"search": "Search",
        "path": "Path",
        "root": "Root",
        "up": "Up",
        "folder": "Folder",
        "new_folder": "New Folder",
        "folder_name": "Folder Name",
        "create": "Create",
        "copy_key": "Copy Key",
        "copy_url": "Copy URL",
        "copy_presigned": "Copy Presigned Link",
        "rename_move": "Rename / Move",
        "destination_key": "Destination Key",
        "move": "Move",
        "details": "Details",
        "content_type": "Content-Type",
        "etag": "ETag",
        "metadata": "Metadata",
        "upload_progress": "Uploading %d of %d",
        "cancel_upload": "Cancel Upload",
        "retry_failed": "Retry Failed",
        "upload_failed_count": "%d upload failed",
        "drop_to_upload": "Drop files to upload",
        "presigned_copied": "Presigned link copied",
        "copied": "Copied",
        "download": "Download",
        "batch_delete_confirm_title": "Delete selected objects?",
        "batch_delete_confirm_message": "This removes the selected objects from the remote bucket.",
        "favorite": "Favorite",
        "favorites": "Favorites",
        "recent": "Recent",
        "history": "History",
        "test_connection": "Test Connection",
        "connection_ok": "Connection succeeded",
        "export_config": "Export Config",
        "import_config": "Import Config",
        "cloudflare_template": "R2 Template",
        "usage": "Usage",
        "objects_count": "%d objects",
        "overwrite_title": "Files already exist",
        "overwrite_message": "Choose how to handle files with the same object key.",
        "replace": "Replace",
        "auto_rename": "Auto Rename",
        "download_done": "Download complete",
        "operation_done": "Operation complete"
    ]

    private static let zh: [String: String] = [
        "app_name": "R2Desk",
        "sidebar_title": "存储桶",
        "add_bucket": "添加 Bucket",
        "settings": "设置",
        "refresh": "刷新",
        "upload": "上传",
        "open": "打开",
        "delete": "删除",
        "empty_title": "选择或添加 Bucket",
        "empty_message": "S3 和 Cloudflare R2 配置只保存在这台 Mac 本地。",
        "no_objects": "这个 Bucket 里还没有文件",
        "name": "名称",
        "size": "大小",
        "modified": "修改时间",
        "storage_class": "存储类型",
        "status_ready": "就绪",
        "status_loading": "正在加载文件...",
        "status_uploading": "正在上传...",
        "status_opening": "正在打开文件...",
        "profile_name": "连接名称",
        "display_name": "显示名称",
        "bucket_name": "Bucket 名称",
        "endpoint": "Endpoint 地址",
        "region": "区域",
        "access_key": "Access Key ID",
        "secret_key": "Secret Access Key",
        "save": "保存",
        "cancel": "取消",
        "new_bucket": "新建 Bucket",
        "edit_bucket": "Bucket 设置",
        "delete_confirm_title": "删除文件？",
        "delete_confirm_message": "这会从远程 Bucket 删除当前选中的文件。",
        "error_title": "操作失败",
        "delete_bucket": "移除 Bucket",
        "delete_bucket_confirm_title": "从 R2Desk 移除 Bucket？",
        "delete_bucket_confirm_message": "只会删除本地配置和钥匙串凭据，不会影响远程文件。",
        "local_only": "本地配置 + 钥匙串"
        ,"search": "搜索",
        "path": "路径",
        "root": "根目录",
        "up": "上一级",
        "folder": "文件夹",
        "new_folder": "新建文件夹",
        "folder_name": "文件夹名称",
        "create": "创建",
        "copy_key": "复制 Key",
        "copy_url": "复制 URL",
        "copy_presigned": "复制预签名链接",
        "rename_move": "重命名 / 移动",
        "destination_key": "目标 Key",
        "move": "移动",
        "details": "详情",
        "content_type": "Content-Type",
        "etag": "ETag",
        "metadata": "Metadata",
        "upload_progress": "正在上传 %d / %d",
        "cancel_upload": "取消上传",
        "retry_failed": "重试失败项",
        "upload_failed_count": "%d 个文件上传失败",
        "drop_to_upload": "松开即可上传",
        "presigned_copied": "预签名链接已复制",
        "copied": "已复制",
        "download": "下载",
        "batch_delete_confirm_title": "删除选中的文件？",
        "batch_delete_confirm_message": "这会从远程 Bucket 删除选中的文件。",
        "favorite": "收藏",
        "favorites": "收藏",
        "recent": "最近",
        "history": "操作记录",
        "test_connection": "测试连接",
        "connection_ok": "连接成功",
        "export_config": "导出配置",
        "import_config": "导入配置",
        "cloudflare_template": "R2 模板",
        "usage": "用量",
        "objects_count": "%d 个对象",
        "overwrite_title": "文件已存在",
        "overwrite_message": "请选择同名 Object Key 的处理方式。",
        "replace": "替换",
        "auto_rename": "自动改名",
        "download_done": "下载完成",
        "operation_done": "操作完成"
    ]
}
